### ISSUE TITLE
Supported Node version

### ISSUE THREAD

**Issue by gilisho** [corevo/docker-compose-testkit#5]
Hi Tomer!

I want to experiment with this testkit, but when trying to install it on my project with `yarn add` command it fails because my project runs with Node v14.
Is there any reason to have the `engines` field in `package.json` to include only version 16 and not 14?

Looks like a great testkit BTW!

**Comment by corevo** [comment]
There's no reason it shouldn't work, it only requires ESM on your side, I've kept it that way because that's the node version I use and I didn't set up CI yet.

I've fixed the engines field, lmk what you make of it.
